//LOCALHOST
### Get all Contacts
GET http://localhost:3000/mongo

### Get Contact by Id
GET http://localhost:3000/mongo/6967e4b37d47d9b130a86ff1

### Create Contact
POST http://localhost:3000/mongo HTTP/1.1
Content-Type: application/json

{
    "firstName": "Grayson",
    "lastName": "Hadley",
    "email": "grayhad@email.com",
    "favoriteColor": "Sky Blue",
    "birthday": "10/22/1985"
}

### Update Contact
PUT http://localhost:3000/mongo/696931a70bdd4dff96186010
Content-Type: application/json

{
    "firstName": "Graysen",
    "lastName": "Hadlay",
    "email": "grayhad@realemail.com",
    "favoriteColor": "Purple",
    "birthday": "10/21/1985"
}

### Delete Contact
DELETE http://localhost:3000/mongo/696931a70bdd4dff96186010

